/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author edu
 */
public class Screen_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Screen_GUI
     */
    public Screen_GUI() {
        initComponents();
        Meia1_cb.setVisible(false);
        Meia2_cb.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Princ_Panel = new javax.swing.JTabbedPane();
        Pedidos_Jpanel = new javax.swing.JPanel();
        labelHeader1 = new org.edisoncor.gui.label.LabelHeader();
        labelTask1 = new org.edisoncor.gui.label.LabelTask();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        numCliente_txt = new org.edisoncor.gui.textField.TextFieldRoundBackground();
        Acompanhamentos = new org.edisoncor.gui.comboBox.ComboBoxRect();
        Meia1_cb = new org.edisoncor.gui.comboBox.ComboBoxRect();
        Meia2_cb = new org.edisoncor.gui.comboBox.ComboBoxRect();
        jLabel4 = new javax.swing.JLabel();
        Preco_txt = new org.edisoncor.gui.textField.TextFieldRoundBackground();
        send_btn = new org.edisoncor.gui.button.ButtonAction();
        jLabel5 = new javax.swing.JLabel();
        Princ_options = new org.edisoncor.gui.comboBox.ComboBoxRect();
        qtdPizzas_txt = new org.edisoncor.gui.textField.TextFieldRoundBackground();
        jLabel8 = new javax.swing.JLabel();
        Sair1 = new javax.swing.JButton();
        Entregas_Jpanel = new javax.swing.JPanel();
        labelHeader2 = new org.edisoncor.gui.label.LabelHeader();
        labelTask2 = new org.edisoncor.gui.label.LabelTask();
        jLabel6 = new javax.swing.JLabel();
        Pedidos = new org.edisoncor.gui.comboBox.ComboBoxRect();
        gerarpdf_btn = new org.edisoncor.gui.button.ButtonAction();
        Sair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        Pedidos_Jpanel.setBackground(new java.awt.Color(255, 255, 255));
        Pedidos_Jpanel.setBorder(new org.edisoncor.gui.util.DropShadowBorder());
        Pedidos_Jpanel.setLayout(null);

        labelHeader1.setText("Organizar Pedidos");
        Pedidos_Jpanel.add(labelHeader1);
        labelHeader1.setBounds(1, 1, 753, 17);

        labelTask1.setText("Gerencie e Realize os pedidos de clientes");
        labelTask1.setToolTipText("");
        labelTask1.setDescription("Selecione e faça os pedidos");
        Pedidos_Jpanel.add(labelTask1);
        labelTask1.setBounds(1, 24, 458, 64);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Quantidade de pizzas:");
        Pedidos_Jpanel.add(jLabel2);
        jLabel2.setBounds(11, 155, 124, 30);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Número do cliente:");
        Pedidos_Jpanel.add(jLabel3);
        jLabel3.setBounds(29, 213, 106, 30);

        numCliente_txt.setDescripcion("(DDD) 12345-7890");
        numCliente_txt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Pedidos_Jpanel.add(numCliente_txt);
        numCliente_txt.setBounds(139, 214, 191, 30);

        Acompanhamentos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Refrigerante", "Salgado", "Doce", "Nenhum" }));
        Acompanhamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcompanhamentosActionPerformed(evt);
            }
        });
        Pedidos_Jpanel.add(Acompanhamentos);
        Acompanhamentos.setBounds(390, 190, 109, 20);

        Meia1_cb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mussarela", "Queijo", "Bacon", "Portuguesa" }));
        Pedidos_Jpanel.add(Meia1_cb);
        Meia1_cb.setBounds(231, 104, 109, 20);

        Meia2_cb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mussarela", "Queijo", "Bacon", "Portuguesa" }));
        Pedidos_Jpanel.add(Meia2_cb);
        Meia2_cb.setBounds(346, 104, 109, 20);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Preço:");
        Pedidos_Jpanel.add(jLabel4);
        jLabel4.setBounds(98, 262, 37, 30);

        Preco_txt.setBackground(new java.awt.Color(153, 153, 153));
        Preco_txt.setForeground(new java.awt.Color(255, 255, 255));
        Preco_txt.setDescripcion("O preço aparecerá aqui");
        Preco_txt.setEnabled(false);
        Preco_txt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Preco_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Preco_txtActionPerformed(evt);
            }
        });
        Pedidos_Jpanel.add(Preco_txt);
        Preco_txt.setBounds(139, 263, 191, 30);

        send_btn.setBackground(new java.awt.Color(255, 255, 255));
        send_btn.setText("Enviar pedido");
        send_btn.setColorDeSombra(new java.awt.Color(255, 255, 255));
        send_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                send_btnActionPerformed(evt);
            }
        });
        Pedidos_Jpanel.add(send_btn);
        send_btn.setBounds(520, 330, 153, 35);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("Selecione a pizza:");
        Pedidos_Jpanel.add(jLabel5);
        jLabel5.setBounds(11, 99, 101, 30);

        Princ_options.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mussarela", "Queijo", "Bacon", "Portuguesa", "Meia-Meia" }));
        Princ_options.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Princ_optionsActionPerformed(evt);
            }
        });
        Pedidos_Jpanel.add(Princ_options);
        Princ_options.setBounds(116, 104, 109, 20);

        qtdPizzas_txt.setDescripcion("__________________________");
        qtdPizzas_txt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        qtdPizzas_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtdPizzas_txtActionPerformed(evt);
            }
        });
        Pedidos_Jpanel.add(qtdPizzas_txt);
        qtdPizzas_txt.setBounds(139, 156, 190, 30);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setText("Selecione o acompanhamento:");
        Pedidos_Jpanel.add(jLabel8);
        jLabel8.setBounds(390, 150, 180, 30);

        Sair1.setBackground(new java.awt.Color(255, 0, 0));
        Sair1.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        Sair1.setForeground(new java.awt.Color(255, 255, 255));
        Sair1.setText("X");
        Sair1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 0, 0), new java.awt.Color(255, 0, 0), new java.awt.Color(255, 0, 0), new java.awt.Color(255, 0, 0)));
        Sair1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sair1ActionPerformed(evt);
            }
        });
        Pedidos_Jpanel.add(Sair1);
        Sair1.setBounds(660, 30, 54, 34);

        Princ_Panel.addTab("Pedido", Pedidos_Jpanel);

        Entregas_Jpanel.setBackground(new java.awt.Color(255, 255, 255));
        Entregas_Jpanel.setBorder(new org.edisoncor.gui.util.DropShadowBorder());
        Entregas_Jpanel.setLayout(null);

        labelHeader2.setText("Orgnaizar entregas");
        Entregas_Jpanel.add(labelHeader2);
        labelHeader2.setBounds(1, 1, 738, 17);

        labelTask2.setText("Finalize os pedidos e Realiza a entrega");
        labelTask2.setDescription("Finalize as entregas e faça o comprovante");
        Entregas_Jpanel.add(labelTask2);
        labelTask2.setBounds(1, 24, 418, 64);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("Escolha um pedido:");
        Entregas_Jpanel.add(jLabel6);
        jLabel6.setBounds(27, 121, 113, 24);
        Entregas_Jpanel.add(Pedidos);
        Pedidos.setBounds(144, 123, 239, 20);

        gerarpdf_btn.setText("Gerar PDF");
        gerarpdf_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerarpdf_btnActionPerformed(evt);
            }
        });
        Entregas_Jpanel.add(gerarpdf_btn);
        gerarpdf_btn.setBounds(500, 310, 153, 35);

        Sair.setBackground(new java.awt.Color(255, 0, 0));
        Sair.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        Sair.setForeground(new java.awt.Color(255, 255, 255));
        Sair.setText("X");
        Sair.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 0, 0), new java.awt.Color(255, 0, 0), new java.awt.Color(255, 0, 0), new java.awt.Color(255, 0, 0)));
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });
        Entregas_Jpanel.add(Sair);
        Sair.setBounds(660, 30, 54, 34);

        Princ_Panel.addTab("Entregas", Entregas_Jpanel);

        getContentPane().add(Princ_Panel);
        Princ_Panel.setBounds(0, 0, 750, 420);

        setSize(new java.awt.Dimension(745, 413));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AcompanhamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcompanhamentosActionPerformed
       
    }//GEN-LAST:event_AcompanhamentosActionPerformed

    private void send_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_send_btnActionPerformed
        
    }//GEN-LAST:event_send_btnActionPerformed

    private void Princ_optionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Princ_optionsActionPerformed
        Model.Functions_DAO.meia(Princ_options.getSelectedItem().toString());
    }//GEN-LAST:event_Princ_optionsActionPerformed

    private void qtdPizzas_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtdPizzas_txtActionPerformed

    }//GEN-LAST:event_qtdPizzas_txtActionPerformed

    private void Preco_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Preco_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Preco_txtActionPerformed

    private void Sair1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sair1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_Sair1ActionPerformed

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SairActionPerformed

    private void gerarpdf_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerarpdf_btnActionPerformed
        Model.Functions_DAO.pdf();
    }//GEN-LAST:event_gerarpdf_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Screen_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Screen_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Screen_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Screen_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Screen_GUI().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static org.edisoncor.gui.comboBox.ComboBoxRect Acompanhamentos;
    private javax.swing.JPanel Entregas_Jpanel;
    public static org.edisoncor.gui.comboBox.ComboBoxRect Meia1_cb;
    public static org.edisoncor.gui.comboBox.ComboBoxRect Meia2_cb;
    private org.edisoncor.gui.comboBox.ComboBoxRect Pedidos;
    private javax.swing.JPanel Pedidos_Jpanel;
    public static org.edisoncor.gui.textField.TextFieldRoundBackground Preco_txt;
    private javax.swing.JTabbedPane Princ_Panel;
    public static org.edisoncor.gui.comboBox.ComboBoxRect Princ_options;
    private javax.swing.JButton Sair;
    private javax.swing.JButton Sair1;
    private org.edisoncor.gui.button.ButtonAction gerarpdf_btn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private org.edisoncor.gui.label.LabelHeader labelHeader1;
    private org.edisoncor.gui.label.LabelHeader labelHeader2;
    private org.edisoncor.gui.label.LabelTask labelTask1;
    private org.edisoncor.gui.label.LabelTask labelTask2;
    public static org.edisoncor.gui.textField.TextFieldRoundBackground numCliente_txt;
    public static org.edisoncor.gui.textField.TextFieldRoundBackground qtdPizzas_txt;
    private org.edisoncor.gui.button.ButtonAction send_btn;
    // End of variables declaration//GEN-END:variables
}
