/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author edu
 */
public class Screen_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Screen_GUI
     */
    public Screen_GUI() {
        initComponents();
        Meia1_cb.setVisible(false);
        Meia2_cb.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Princ_Panel = new javax.swing.JTabbedPane();
        Pedidos_Jpanel = new javax.swing.JPanel();
        Send_btn = new javax.swing.JButton();
        labelHeader1 = new org.edisoncor.gui.label.LabelHeader();
        labelTask1 = new org.edisoncor.gui.label.LabelTask();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textFieldRoundBackground1 = new org.edisoncor.gui.textField.TextFieldRoundBackground();
        textFieldRoundBackground2 = new org.edisoncor.gui.textField.TextFieldRoundBackground();
        Princ_options = new org.edisoncor.gui.comboBox.ComboBoxRect();
        Meia1_cb = new org.edisoncor.gui.comboBox.ComboBoxRect();
        Meia2_cb = new org.edisoncor.gui.comboBox.ComboBoxRect();
        Entregas_Jpanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        Pedidos_Jpanel.setBorder(new org.edisoncor.gui.util.DropShadowBorder());

        Send_btn.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        Send_btn.setText("Finalizar Pedido");

        labelHeader1.setText("Organizar Pedidos");

        labelTask1.setText("Gerencie e Realize os pedidos de clientes");
        labelTask1.setToolTipText("");
        labelTask1.setDescription("Selecione e faça os pedidos");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Selecione a pizza:");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Quantidade de pizzas:");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Número do cliente:");

        textFieldRoundBackground1.setDescripcion("(DDD) 12345-7890");

        textFieldRoundBackground2.setDescripcion("__________________________");
        textFieldRoundBackground2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldRoundBackground2ActionPerformed(evt);
            }
        });

        Princ_options.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mussarela", "Queijo", "Bacon", "Portuguesa", "Meia-Meia" }));
        Princ_options.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Princ_optionsActionPerformed(evt);
            }
        });

        Meia1_cb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mussarela", "Queijo", "Bacon", "Portuguesa" }));

        Meia2_cb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mussarela", "Queijo", "Bacon", "Portuguesa" }));

        javax.swing.GroupLayout Pedidos_JpanelLayout = new javax.swing.GroupLayout(Pedidos_Jpanel);
        Pedidos_Jpanel.setLayout(Pedidos_JpanelLayout);
        Pedidos_JpanelLayout.setHorizontalGroup(
            Pedidos_JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pedidos_JpanelLayout.createSequentialGroup()
                .addGroup(Pedidos_JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelHeader1, javax.swing.GroupLayout.PREFERRED_SIZE, 753, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTask1, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(Pedidos_JpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Pedidos_JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Pedidos_JpanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFieldRoundBackground1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Pedidos_JpanelLayout.createSequentialGroup()
                        .addGroup(Pedidos_JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Pedidos_JpanelLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldRoundBackground2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Pedidos_JpanelLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Princ_options, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Meia1_cb, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Meia2_cb, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pedidos_JpanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Send_btn)
                .addGap(55, 55, 55))
        );
        Pedidos_JpanelLayout.setVerticalGroup(
            Pedidos_JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pedidos_JpanelLayout.createSequentialGroup()
                .addComponent(labelHeader1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelTask1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Pedidos_JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Princ_options, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Meia1_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Meia2_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(Pedidos_JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldRoundBackground2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(Pedidos_JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldRoundBackground1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(Send_btn)
                .addGap(25, 25, 25))
        );

        Princ_Panel.addTab("Pedido", Pedidos_Jpanel);

        javax.swing.GroupLayout Entregas_JpanelLayout = new javax.swing.GroupLayout(Entregas_Jpanel);
        Entregas_Jpanel.setLayout(Entregas_JpanelLayout);
        Entregas_JpanelLayout.setHorizontalGroup(
            Entregas_JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 745, Short.MAX_VALUE)
        );
        Entregas_JpanelLayout.setVerticalGroup(
            Entregas_JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 392, Short.MAX_VALUE)
        );

        Princ_Panel.addTab("Entregas", Entregas_Jpanel);

        getContentPane().add(Princ_Panel);
        Princ_Panel.setBounds(0, 0, 750, 420);

        setSize(new java.awt.Dimension(745, 413));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldRoundBackground2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldRoundBackground2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldRoundBackground2ActionPerformed

    private void Princ_optionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Princ_optionsActionPerformed
        Model.Functions_DAO.meia(Princ_options.getSelectedItem().toString());
    }//GEN-LAST:event_Princ_optionsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Screen_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Screen_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Screen_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Screen_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Screen_GUI().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Entregas_Jpanel;
    public static org.edisoncor.gui.comboBox.ComboBoxRect Meia1_cb;
    public static org.edisoncor.gui.comboBox.ComboBoxRect Meia2_cb;
    private javax.swing.JPanel Pedidos_Jpanel;
    private javax.swing.JTabbedPane Princ_Panel;
    public static org.edisoncor.gui.comboBox.ComboBoxRect Princ_options;
    private javax.swing.JButton Send_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private org.edisoncor.gui.label.LabelHeader labelHeader1;
    private org.edisoncor.gui.label.LabelTask labelTask1;
    private org.edisoncor.gui.textField.TextFieldRoundBackground textFieldRoundBackground1;
    private org.edisoncor.gui.textField.TextFieldRoundBackground textFieldRoundBackground2;
    // End of variables declaration//GEN-END:variables
}
